### ISSUE TITLE
Can't connect master node ?

### ISSUE THREAD

**Issue by receperdogan** [Storidge/cio-user-docs#2]
Hi there,

I tried to setup cio cluster and i got some problems.
When i did `cioctl create` on primary node i am getting token no problem.
But on second node i tried `cioctl join xx.xx.xx.xx TOKENXX` that gives me 

> Cannot connect to xx.xx.xx.xx. Retry command or check for connectivity and routing issues

Can you help me?

**Comment by rerdogantr** [comment]
`weqwe`
